# NumPy
NumPy stand for Numerical Python
NumPy uses in Algebra,transform and matrices.

In [1]:
import numpy as pp
num = pp.array([1,2,33,4,5])
print(num)
print(pp.__version__)

[ 1  2 33  4  5]
1.16.5


In [7]:
import numpy as np
arr = np.array((1,2,3,4,5,6,7))
zeroD = np.array(45)
print(arr)
print(zeroD)

[1 2 3 4 5 6 7]
45


In [21]:
import numpy as np
two_D = np.array([[1,2,3,4],[5,6,7,8]])
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[11,22,33],[44,55,66]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(two_D.ndim)

0
1
2
4
2


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=8)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[1 2 3 4]]]]]]]]
number of dimensions : 8


In [36]:
import numpy as np 
numb_array = np.array([1,2,3,4,5], ndmin = 5)
print(numb_array)
print('Number of Dimensions:', numb_array.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Dimensions: 5


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1]+arr[3])

6


In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print(arr[1])

print('2nd element on 1st dim: ', arr[0, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
2nd element on 1st dim:  3


# Negative Slicing 

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:1])

[]


# Slicing 2-D Array 

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])
print(arr)
print(arr[2][3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
14


In [2]:
import pandas as pd
data = [['tom', 10,' matric, fsc, bs'], ['nick', 15,'matric, fsc'], ['juli', 14,'matric'],['juli', 14,'mat,ffsc,bs,ms,phd']]
 
# Create the pandas DataFrame
dff = pd.DataFrame(data, columns = ['Name', 'Age','Education_level'])
# edu = pd.DataFrame(data, columns = ['Education_level'])
df['Education_level-1'] = df['Education_level'].map(lambda x:x.split(',')[0])
column = df["Education_level"].values[0:4]
column

NameError: name 'df' is not defined

In [3]:
import pandas as pd
data = [['tom', 10,' matric, fsc, bs'], ['nick', 15,'matric, fsc'], ['juli', 14,'matric'],['juli', 14,'mat,ffsc,bs,ms,phd']]
 
# Create the pandas DataFrame
dff = pd.DataFrame(data, columns = ['Name', 'Age','Education_level'])
# edu = pd.DataFrame(data, columns = ['Education_level'])
df['Education_level-1'] = df['Education_level'].map(lambda x:x.split(',')[0])

df

NameError: name 'df' is not defined